name: CI|Deploy heroku

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Bundler
      run: |
        git add .
        git commit
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/youtube-d0wnload.git master
