name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: akhileshns/heroku-deploy@master # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "youtube-d0wnload"
            heroku_email: "hosegy93@gmail.com"
            buildpack: "heroku/python"
