name: CI | Deploy heroku

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploying
      run: |
        git config --global user.email "hosegy93@gmail.com"
        git config --global user.name "Hossam Ahmad"
        git add .
        git commit -am "deploy" 
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/youtube-d0wnload.git HEAD:master
